using ICSharpCode.Decompiler.TypeSystem;

namespace ILens;

/// <summary>
/// Recognizes types Roslyn, Unity, and Burst emit that aren't part of an
/// assembly's intended public surface — closures, anonymous types, iterator
/// state machines, source-generator output. Centralized so <c>list_types</c>,
/// <c>search_types</c>, and <c>list_changed_types</c> agree on what counts as
/// noise and so future tools that enumerate types pick up the same definition.
/// </summary>
public static class CompilerGeneratedFilter
{
    /// <summary>
    /// Human-readable summary of what this filter recognizes. Embedded into the
    /// description text of every tool that exposes the flag, so callers know
    /// the exact rules without reading source.
    /// </summary>
    public const string PatternsDescription =
        "[CompilerGenerated] attribute; any Roslyn synthetic name (starts with '<' — covers " +
        "<>c, <>c__DisplayClass*, <>f__AnonymousType*, <PrivateImplementationDetails>, iterator " +
        "and async state machines like <MethodName>d__N); UnitySourceGeneratedAssembly*, " +
        "__JobReflectionRegistrationOutput*, BurstDirectCallInitializer*; Burst direct-call " +
        "wrapper nested types whose name contains $BurstDirectCall or $PostfixBurstDelegate. " +
        "Nested types inherit the verdict — a nested type inside any compiler-generated outer " +
        "type is also excluded.";

    /// <summary>
    /// Is this type compiler-generated by the recognized patterns? Walks the
    /// nesting chain — a nested type inside a generated outer is also generated,
    /// catching cases (e.g. ECMA-suffixed inner helpers in
    /// <c>&lt;PrivateImplementationDetails&gt;</c>) where the inner name itself
    /// doesn't match the prefix list.
    /// </summary>
    public static bool IsCompilerGenerated(ITypeDefinition type)
    {
        for (var t = type; t != null; t = t.DeclaringTypeDefinition)
        {
            if (t.HasAttribute(KnownAttribute.CompilerGenerated)) return true;
            if (IsGeneratedName(t.Name)) return true;
        }
        return false;
    }

    private static bool IsGeneratedName(string name)
    {
        if (string.IsNullOrEmpty(name)) return false;
        // Roslyn convention: every synthetic name starts with '<' — anonymous
        // types, closures, display classes, iterator state machines, async
        // state machines, and the assembly-wide <PrivateImplementationDetails>
        // all share this. A real C# identifier can't start with '<', so the
        // single-character check is correct, not just a heuristic.
        if (name[0] == '<') return true;
        if (name.StartsWith("UnitySourceGeneratedAssembly", StringComparison.Ordinal)) return true;
        if (name.StartsWith("__JobReflectionRegistrationOutput", StringComparison.Ordinal)) return true;
        if (name.StartsWith("BurstDirectCallInitializer", StringComparison.Ordinal)) return true;
        // Burst direct-call wrapper nested types — declaring type is a regular
        // user class (e.g. RimWorld.MapGenUtility), so the chain-walk above
        // can't catch them via the outer type; the wrapper's own name carries
        // a '$'-bearing suffix Burst's source generator emits. '$' is not a
        // valid C# identifier character, so the Contains check has no
        // false-positive risk on hand-written code.
        if (name.Contains("$BurstDirectCall", StringComparison.Ordinal)) return true;
        if (name.Contains("$PostfixBurstDelegate", StringComparison.Ordinal)) return true;
        return false;
    }
}
